cd "/Volumes/Backup"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1953 Tango de Colección Nº10"
cp -R -f "Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1953 Tango de Colección Nº10/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1953 Tango de Colección Nº10"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 1"
cp -R -f "Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 1/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 2"
cp -R -f "Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 2/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - 1941-1955 Grandes del tango 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Al compas de un tango"
cp -R -f "Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Al compas de un tango/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Al compas de un tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Candombe y Milonga"
cp -R -f "Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Candombe y Milonga/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Alberto Castillo/Alberto Castillo - Candombe y Milonga"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Nelly Omar/Nelly Omar - El día que me quieras-1977"
cp -R -f "Tango Argentin/\$Cantor/Nelly Omar/Nelly Omar - El día que me quieras-1977/" "/Users/michelvargoz/Music/Tango Argentin/\$Cantor/Nelly Omar/Nelly Omar - El día que me quieras-1977"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/A portrait of tango 1 Tangos en frances"
cp -R -f "Tango Argentin/\$Compilation/A portrait of tango 1 Tangos en frances/" "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/A portrait of tango 1 Tangos en frances"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/Candombe de Uruguay"
cp -R -f "Tango Argentin/\$Compilation/Candombe de Uruguay/" "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/Candombe de Uruguay"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/Old World Tangos 1 - Echoes from afar"
cp -R -f "Tango Argentin/\$Compilation/Old World Tangos 1 - Echoes from afar/" "/Users/michelvargoz/Music/Tango Argentin/\$Compilation/Old World Tangos 1 - Echoes from afar"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Cesaria Evora"
cp -R -f "Tango Argentin/\$Cortina/Cesaria Evora/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Cesaria Evora"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Creedence"
cp -R -f "Tango Argentin/\$Cortina/Creedence/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Creedence"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Créole"
cp -R -f "Tango Argentin/\$Cortina/Créole/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Créole"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Erroll Garner"
cp -R -f "Tango Argentin/\$Cortina/Erroll Garner/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Erroll Garner"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Folklore"
cp -R -f "Tango Argentin/\$Cortina/Folklore/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Folklore"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Glenn Miller"
cp -R -f "Tango Argentin/\$Cortina/Glenn Miller/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Glenn Miller"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Hits"
cp -R -f "Tango Argentin/\$Cortina/Hits/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Hits"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Hits Adagio"
cp -R -f "Tango Argentin/\$Cortina/Hits Adagio/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Hits Adagio"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Los pajaros perdidos"
cp -R -f "Tango Argentin/\$Cortina/Los pajaros perdidos/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Los pajaros perdidos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Louis Armstrong"
cp -R -f "Tango Argentin/\$Cortina/Louis Armstrong/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Louis Armstrong"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Mile Davis"
cp -R -f "Tango Argentin/\$Cortina/Mile Davis/" "/Users/michelvargoz/Music/Tango Argentin/\$Cortina/Mile Davis"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Folklore/Los Cantores del Alba 1(folklore)"
cp -R -f "Tango Argentin/\$Folklore/Los Cantores del Alba 1(folklore)/" "/Users/michelvargoz/Music/Tango Argentin/\$Folklore/Los Cantores del Alba 1(folklore)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Folklore/Los Carabajal - 100 años de Chacarera"
cp -R -f "Tango Argentin/\$Folklore/Los Carabajal - 100 años de Chacarera/" "/Users/michelvargoz/Music/Tango Argentin/\$Folklore/Los Carabajal - 100 años de Chacarera"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/\$divers"
cp -R -f "Tango Argentin/\$Orquesta/\$divers/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/\$divers"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club (2002)"
cp -R -f "Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club (2002)/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club (2002)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club - Mar Dulce (2007)"
cp -R -f "Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club - Mar Dulce (2007)/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bajofondo/Bajofondo Tango Club - Mar Dulce (2007)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bianco Bachicha"
cp -R -f "Tango Argentin/\$Orquesta/Bianco Bachicha/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Bianco Bachicha"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Electrocutango Felino"
cp -R -f "Tango Argentin/\$Orquesta/Electrocutango Felino/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Electrocutango Felino"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Ensemble Hyperion - Luis Stazo"
cp -R -f "Tango Argentin/\$Orquesta/Ensemble Hyperion - Luis Stazo/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Ensemble Hyperion - Luis Stazo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Gotan Project/Gotan Project - La Revancha del Tango"
cp -R -f "Tango Argentin/\$Orquesta/Gotan Project/Gotan Project - La Revancha del Tango/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Gotan Project/Gotan Project - La Revancha del Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Narcotango/Carlos Libedinsky - Narcotango"
cp -R -f "Tango Argentin/\$Orquesta/Narcotango/Carlos Libedinsky - Narcotango/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Narcotango/Carlos Libedinsky - Narcotango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1926-1938 RCA Victor 100 Años"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1926-1938 RCA Victor 100 Años/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1926-1938 RCA Victor 100 Años"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1929-1944 Collección 78RPM"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1929-1944 Collección 78RPM/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1929-1944 Collección 78RPM"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1930-1944 Collección 78RPM"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1930-1944 Collección 78RPM/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Tipica Victor - 1930-1944 Collección 78RPM"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1933-1934"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1933-1934/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1933-1934"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1937-1938"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1937-1938/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1937-1938"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1941-1944"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1941-1944/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Tipica Victor/Orquesta Típica Victor-1941-1944"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Típica Pichuco"
cp -R -f "Tango Argentin/\$Orquesta/Orquesta Típica Pichuco/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Orquesta Típica Pichuco"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Otros Aires/Otros Aires dos"
cp -R -f "Tango Argentin/\$Orquesta/Otros Aires/Otros Aires dos/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Otros Aires/Otros Aires dos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Otros Aires/Otros Aires uno"
cp -R -f "Tango Argentin/\$Orquesta/Otros Aires/Otros Aires uno/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Otros Aires/Otros Aires uno"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - El Siguiente"
cp -R -f "Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - El Siguiente/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - El Siguiente"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - Muneca Mecanica"
cp -R -f "Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - Muneca Mecanica/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Roulotte Tango/Roulotte Tango - Muneca Mecanica"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/La Tubatango - Bien Canyengue"
cp -R -f "Tango Argentin/\$Orquesta/Tubatango/La Tubatango - Bien Canyengue/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/La Tubatango - Bien Canyengue"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/Los TubaTango y Thierry Caens - Vientos de Tango"
cp -R -f "Tango Argentin/\$Orquesta/Tubatango/Los TubaTango y Thierry Caens - Vientos de Tango/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/Los TubaTango y Thierry Caens - Vientos de Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/Los Tubatango - En el Palais de Glace"
cp -R -f "Tango Argentin/\$Orquesta/Tubatango/Los Tubatango - En el Palais de Glace/" "/Users/michelvargoz/Music/Tango Argentin/\$Orquesta/Tubatango/Los Tubatango - En el Palais de Glace"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1927-1935 Mi evocación"
cp -R -f "Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1927-1935 Mi evocación/" "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1927-1935 Mi evocación"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1931-1932 Obra RCA V1"
cp -R -f "Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1931-1932 Obra RCA V1/" "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1931-1932 Obra RCA V1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1932-1933  Obra RCA V2"
cp -R -f "Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1932-1933  Obra RCA V2/" "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1932-1933  Obra RCA V2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1933-1934  Obra RCA V3"
cp -R -f "Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1933-1934  Obra RCA V3/" "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - 1933-1934  Obra RCA V3"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - Tango Tunes"
cp -R -f "Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - Tango Tunes/" "/Users/michelvargoz/Music/Tango Argentin/Adolfo Carabelli/Adolfo Carabelli - Tango Tunes"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo Gobbi/Alfredo Gobbi su obra completa"
cp -R -f "Tango Argentin/Alfredo Gobbi/Alfredo Gobbi su obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo Gobbi/Alfredo Gobbi su obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - 24 grandes éxitos"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - 24 grandes éxitos/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - 24 grandes éxitos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - El vals de Nochebuena"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - El vals de Nochebuena/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - El vals de Nochebuena"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Exitos de Oro"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Exitos de Oro/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Exitos de Oro"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Instrumentales inolvidables"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Instrumentales inolvidables/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Instrumentales inolvidables"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Jiron Porteño"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Jiron Porteño/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Jiron Porteño"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Memorias"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Memorias/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - Memorias"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - con sus Grandes Cantantes en FM Tango"
cp -R -f "Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - con sus Grandes Cantantes en FM Tango/" "/Users/michelvargoz/Music/Tango Argentin/Alfredo de Angelis/Alfredo de Angelis - con sus Grandes Cantantes en FM Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Angel d'Agostino/Angel d'Agostino obra completa"
cp -R -f "Tango Argentin/Angel d'Agostino/Angel d'Agostino obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Angel d'Agostino/Angel d'Agostino obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - 1941-1943 Fiorentino de FM tango para usted"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - 1941-1943 Fiorentino de FM tango para usted/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - 1941-1943 Fiorentino de FM tango para usted"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 01 - 1941"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 01 - 1941/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 01 - 1941"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 02 - 1942"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 02 - 1942/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 02 - 1942"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 03 - 1942-1943"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 03 - 1942-1943/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 03 - 1942-1943"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 04 - 1943-1944"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 04 - 1943-1944/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 04 - 1943-1944"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 05 - 1944-1945"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 05 - 1944-1945/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 05 - 1944-1945"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 06 - 1945-1946"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 06 - 1945-1946/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 06 - 1945-1946"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 07 - 1946-1948"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 07 - 1946-1948/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 07 - 1946-1948"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 08 - 1948-1949"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 08 - 1948-1949/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 08 - 1948-1949"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 09 - 1961-1963"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 09 - 1961-1963/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 09 - 1961-1963"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 10 - 1963"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 10 - 1963/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 10 - 1963"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 12 - 1965"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 12 - 1965/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 12 - 1965"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 13 - 1966-1967"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 13 - 1966-1967/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 13 - 1966-1967"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 14 - 1967-1968"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 14 - 1967-1968/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 14 - 1967-1968"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 15 - 1969-1970"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 15 - 1969-1970/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 15 - 1969-1970"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 16 - 1968-1971"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 16 - 1968-1971/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Su obra completa en la RCA Vol 16 - 1968-1971"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Tango Tunes 1943 Uno"
cp -R -f "Tango Argentin/Aníbal Troilo/Anibal Troilo - Tango Tunes 1943 Uno/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Anibal Troilo - Tango Tunes 1943 Uno"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1938 (sello Odeon)"
cp -R -f "Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1938 (sello Odeon)/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1938 (sello Odeon)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952 Tecleando (sello TK)"
cp -R -f "Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952 Tecleando (sello TK)/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952 Tecleando (sello TK)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952-1953 Mano Brava (sello TK)"
cp -R -f "Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952-1953 Mano Brava (sello TK)/" "/Users/michelvargoz/Music/Tango Argentin/Aníbal Troilo/Aníbal Troilo - en los sellos TK, Pampa y Odeon/Anibal Troilo - 1952-1953 Mano Brava (sello TK)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1956-1958 Archivo RCA"
cp -R -f "Tango Argentin/Armando Pontier/Armando Pontier - 1956-1958 Archivo RCA/" "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1956-1958 Archivo RCA"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1957-1958 Archivo Columbia Vol 1"
cp -R -f "Tango Argentin/Armando Pontier/Armando Pontier - 1957-1958 Archivo Columbia Vol 1/" "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1957-1958 Archivo Columbia Vol 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1958-1960 Archivo Columbia Vol 2"
cp -R -f "Tango Argentin/Armando Pontier/Armando Pontier - 1958-1960 Archivo Columbia Vol 2/" "/Users/michelvargoz/Music/Tango Argentin/Armando Pontier/Armando Pontier - 1958-1960 Archivo Columbia Vol 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1946-1948 Su Primera Orquesta Reliquias"
cp -R -f "Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1946-1948 Su Primera Orquesta Reliquias/" "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1946-1948 Su Primera Orquesta Reliquias"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1974 Libertango"
cp -R -f "Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1974 Libertango/" "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1974 Libertango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1982 Original tangos from Argentina"
cp -R -f "Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1982 Original tangos from Argentina/" "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1982 Original tangos from Argentina"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1986 Tango - Zero Hour"
cp -R -f "Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1986 Tango - Zero Hour/" "/Users/michelvargoz/Music/Tango Argentin/Astor Piazzolla/Astor Piazzolla - 1986 Tango - Zero Hour"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos Gardel/Carlos Gardel - Discografia"
cp -R -f "Tango Argentin/Carlos Gardel/Carlos Gardel - Discografia/" "/Users/michelvargoz/Music/Tango Argentin/Carlos Gardel/Carlos Gardel - Discografia"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1943 Colección 78rpm"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1943 Colección 78rpm/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1943 Colección 78rpm"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1947 Colección 78rpm"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1947 Colección 78rpm/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos Di Sarli - 1940-1947 Colección 78rpm"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1943 Sus primeros exitos vol 1 (con Roberto Rufino)"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1943 Sus primeros exitos vol 1 (con Roberto Rufino)/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1943 Sus primeros exitos vol 1 (con Roberto Rufino)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1957 Instrumental vol. 2"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1957 Instrumental vol. 2/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1939-1957 Instrumental vol. 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1940-1943 Sus primeros exitos vol 3"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1940-1943 Sus primeros exitos vol 3/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1940-1943 Sus primeros exitos vol 3"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1947 El señor del Tango"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1947 El señor del Tango/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1947 El señor del Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 1"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 1/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 2"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 2/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1941-1953 Las grandes Orquestas vol 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1943-1948 Colección 78rpm"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1943-1948 Colección 78rpm/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1943-1948 Colección 78rpm"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1956 Archivo RCA"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1956 Archivo RCA/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1956 Archivo RCA"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1957 RCA Victor 100 Anos"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1957 RCA Victor 100 Anos/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1954-1957 RCA Victor 100 Anos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1956-1958 Archivo RCA con Roberto Florio y Jorge Duran"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1956-1958 Archivo RCA con Roberto Florio y Jorge Duran/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1956-1958 Archivo RCA con Roberto Florio y Jorge Duran"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1958 Bahia Blanca"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1958 Bahia Blanca/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - 1958 Bahia Blanca"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - Album inconnu"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - Album inconnu/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - Album inconnu"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - Tango Tunes Champagne Tango"
cp -R -f "Tango Argentin/Carlos di Sarli/Carlos di Sarli - Tango Tunes Champagne Tango/" "/Users/michelvargoz/Music/Tango Argentin/Carlos di Sarli/Carlos di Sarli - Tango Tunes Champagne Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Ciriaco Ortiz/Ciriaco Ortiz - 1931-1955 con su Trio y Los Provincianos"
cp -R -f "Tango Argentin/Ciriaco Ortiz/Ciriaco Ortiz - 1931-1955 con su Trio y Los Provincianos/" "/Users/michelvargoz/Music/Tango Argentin/Ciriaco Ortiz/Ciriaco Ortiz - 1931-1955 con su Trio y Los Provincianos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Domingo Federico/Domingo Federico - 1944-1948 Buenos Aires Tango Club"
cp -R -f "Tango Argentin/Domingo Federico/Domingo Federico - 1944-1948 Buenos Aires Tango Club/" "/Users/michelvargoz/Music/Tango Argentin/Domingo Federico/Domingo Federico - 1944-1948 Buenos Aires Tango Club"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Domingo Federico/Domingo Federico - 1945-1948 con sus cantores"
cp -R -f "Tango Argentin/Domingo Federico/Domingo Federico - 1945-1948 con sus cantores/" "/Users/michelvargoz/Music/Tango Argentin/Domingo Federico/Domingo Federico - 1945-1948 con sus cantores"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Donato Racciatti/Donato Racciatti - Tu corazon (canta Nina Miranda)"
cp -R -f "Tango Argentin/Donato Racciatti/Donato Racciatti - Tu corazon (canta Nina Miranda)/" "/Users/michelvargoz/Music/Tango Argentin/Donato Racciatti/Donato Racciatti - Tu corazon (canta Nina Miranda)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato - 1933-1941 Coleccion 78 RPM"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato - 1933-1941 Coleccion 78 RPM/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato - 1933-1941 Coleccion 78 RPM"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato - 1950-1957 En la decada del '50"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato - 1950-1957 En la decada del '50/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato - 1950-1957 En la decada del '50"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 01(1929)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 01(1929)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 01(1929)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 02(1929-1930)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 02(1929-1930)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 02(1929-1930)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 04(1930-1934)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 04(1930-1934)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 04(1930-1934)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 05(1934-1936)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 05(1934-1936)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 05(1934-1936)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 06(1936-1939)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 06(1936-1939)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 06(1936-1939)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 07(1939-1942)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 07(1939-1942)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 07(1939-1942)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 08(1942-1952)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 08(1942-1952)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 08(1942-1952)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 09(1953-1961)"
cp -R -f "Tango Argentin/Edgardo Donato/Edgardo Donato Vol 09(1953-1961)/" "/Users/michelvargoz/Music/Tango Argentin/Edgardo Donato/Edgardo Donato Vol 09(1953-1961)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Elvino Vardaro/Elvino Vardaro - 1928-1943 El violin mayor del tango"
cp -R -f "Tango Argentin/Elvino Vardaro/Elvino Vardaro - 1928-1943 El violin mayor del tango/" "/Users/michelvargoz/Music/Tango Argentin/Elvino Vardaro/Elvino Vardaro - 1928-1943 El violin mayor del tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Francini/Francini-Pontier obra completa"
cp -R -f "Tango Argentin/Enrique Francini/Francini-Pontier obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Francini/Francini-Pontier obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1939 El Chato Flores en el Recuerdo"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1939 El Chato Flores en el Recuerdo/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1939 El Chato Flores en el Recuerdo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1944 De poder a poder"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1944 De poder a poder/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1937-1944 De poder a poder"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1939-1971 Los Reyes del Fox"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1939-1971 Los Reyes del Fox/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1939-1971 Los Reyes del Fox"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1940-1946 Tangos, valses y milongas Reliquias"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1940-1946 Tangos, valses y milongas Reliquias/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - 1940-1946 Tangos, valses y milongas Reliquias"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - Su obra Completa"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - Su obra Completa/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodriguez - Su obra Completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1937-1941 Esto es puro compás"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1937-1941 Esto es puro compás/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1937-1941 Esto es puro compás"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1938-1957 Bailando Lo mejor"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1938-1957 Bailando Lo mejor/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1938-1957 Bailando Lo mejor"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1940-1945 Recordando sus éxitos"
cp -R -f "Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1940-1945 Recordando sus éxitos/" "/Users/michelvargoz/Music/Tango Argentin/Enrique Rodriguez/Enrique Rodríguez - 1940-1945 Recordando sus éxitos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Esteban Morgado/Esteban Morgado - Milongueros"
cp -R -f "Tango Argentin/Esteban Morgado/Esteban Morgado - Milongueros/" "/Users/michelvargoz/Music/Tango Argentin/Esteban Morgado/Esteban Morgado - Milongueros"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Florindo Sassone/Florindo Sassone - Su obra"
cp -R -f "Tango Argentin/Florindo Sassone/Florindo Sassone - Su obra/" "/Users/michelvargoz/Music/Tango Argentin/Florindo Sassone/Florindo Sassone - Su obra"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1931-1959 Sentimiento Gaucho"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1931-1959 Sentimiento Gaucho/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1931-1959 Sentimiento Gaucho"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1938 La Melodia De Nuestro Adiós"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1938 La Melodia De Nuestro Adiós/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1938 La Melodia De Nuestro Adiós"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1953 Cuartito Azul"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1953 Cuartito Azul/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1933-1953 Cuartito Azul"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1935 Poema canta Roberto Maida"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1935 Poema canta Roberto Maida/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1935 Poema canta Roberto Maida"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1937-1941 Nobleza De Arrabal"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1937-1941 Nobleza De Arrabal/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1937-1941 Nobleza De Arrabal"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Candombe"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Candombe/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Candombe"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Evocando el cuarenta"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Evocando el cuarenta/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1941-1949 Evocando el cuarenta"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1945 Que me quiten lo bailao (canta Carlos Roldan)"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1945 Que me quiten lo bailao (canta Carlos Roldan)/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1945 Que me quiten lo bailao (canta Carlos Roldan)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1953 Milongueando Con Canaro Reliquias"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1953 Milongueando Con Canaro Reliquias/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1942-1953 Milongueando Con Canaro Reliquias"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1951-1956 Tiempos viejos"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - 1951-1956 Tiempos viejos/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - 1951-1956 Tiempos viejos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Alberto Arenas"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Alberto Arenas/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Alberto Arenas"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Carlos Roldan"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Carlos Roldan/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Carlos Roldan"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Charlo"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Charlo/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Charlo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Eduardo Adrian"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Eduardo Adrian/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Eduardo Adrian"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Ernesto Famá"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Ernesto Famá/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Ernesto Famá"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Francisco Amor"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Francisco Amor/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Francisco Amor"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales de colección"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales de colección/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales de colección"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales para bailar"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales para bailar/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Instrumentales para bailar"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Roberto Maida"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Roberto Maida/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Roberto Maida"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol1 Todo milonga"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol1 Todo milonga/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol1 Todo milonga"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol2 Todo Vals"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol2 Todo Vals/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Serie para baile Vol2 Todo Vals"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Tangos Del Tiempo Viejo"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - Tangos Del Tiempo Viejo/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - Tangos Del Tiempo Viejo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - con Cantores"
cp -R -f "Tango Argentin/Francisco Canaro/Francisco Canaro - con Cantores/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Francisco Canaro - con Cantores"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Quinteto Pirincho - Tango, valses y milongas"
cp -R -f "Tango Argentin/Francisco Canaro/Quinteto Pirincho - Tango, valses y milongas/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Quinteto Pirincho - Tango, valses y milongas"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Quinteto Pirincho y Quinteto Don Pancho(1937-1952)"
cp -R -f "Tango Argentin/Francisco Canaro/Quinteto Pirincho y Quinteto Don Pancho(1937-1952)/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Canaro/Quinteto Pirincho y Quinteto Don Pancho(1937-1952)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1930 y su orchesta tipica"
cp -R -f "Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1930 y su orchesta tipica/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1930 y su orchesta tipica"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1938 Amor y celos"
cp -R -f "Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1938 Amor y celos/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1938 Amor y celos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1940 y su orchesta tipica"
cp -R -f "Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1940 y su orchesta tipica/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1927-1940 y su orchesta tipica"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1935-1945 RCA Club"
cp -R -f "Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1935-1945 RCA Club/" "/Users/michelvargoz/Music/Tango Argentin/Francisco Lomuto/Francisco Lomuto - 1935-1945 RCA Club"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Fulvio Salamanca/Fulvio Salamanca - Sus grandes exitos"
cp -R -f "Tango Argentin/Fulvio Salamanca/Fulvio Salamanca - Sus grandes exitos/" "/Users/michelvargoz/Music/Tango Argentin/Fulvio Salamanca/Fulvio Salamanca - Sus grandes exitos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - 20 grandes Exitos vol 1"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - 20 grandes Exitos vol 1/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - 20 grandes Exitos vol 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 1"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 1/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 2"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 2/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Columbia Vol. 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Es mi tormento"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Es mi tormento/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Es mi tormento"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 1"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 1/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 2"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 2/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Grandes del Tango vol 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Paciencia"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Paciencia/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Paciencia"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Patio porteño"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Patio porteño/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Patio porteño"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Serie de Oro"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela - Serie de Oro/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela - Serie de Oro"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela y sus cantores y A. Di Paulo"
cp -R -f "Tango Argentin/Hector Varela/Hector Varela y sus cantores y A. Di Paulo/" "/Users/michelvargoz/Music/Tango Argentin/Hector Varela/Hector Varela y sus cantores y A. Di Paulo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - 20 of best tangos argentinos"
cp -R -f "Tango Argentin/Hugo Diaz/Hugo Diaz - 20 of best tangos argentinos/" "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - 20 of best tangos argentinos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - Divina Classical Tango"
cp -R -f "Tango Argentin/Hugo Diaz/Hugo Diaz - Divina Classical Tango/" "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - Divina Classical Tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - Tangos"
cp -R -f "Tango Argentin/Hugo Diaz/Hugo Diaz - Tangos/" "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - Tangos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - en Buenos Aires 1"
cp -R -f "Tango Argentin/Hugo Diaz/Hugo Diaz - en Buenos Aires 1/" "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Diaz - en Buenos Aires 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Díaz - La Armónica del mundo"
cp -R -f "Tango Argentin/Hugo Diaz/Hugo Díaz - La Armónica del mundo/" "/Users/michelvargoz/Music/Tango Argentin/Hugo Diaz/Hugo Díaz - La Armónica del mundo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan Carlos Caceres/Caceres - Tango Negro Trio"
cp -R -f "Tango Argentin/Juan Carlos Caceres/Caceres - Tango Negro Trio/" "/Users/michelvargoz/Music/Tango Argentin/Juan Carlos Caceres/Caceres - Tango Negro Trio"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan Carlos Caceres/Caceres - Tango Négro"
cp -R -f "Tango Argentin/Juan Carlos Caceres/Caceres - Tango Négro/" "/Users/michelvargoz/Music/Tango Argentin/Juan Carlos Caceres/Caceres - Tango Négro"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan Maglio/Juan Maglio - 1927-1932 La Guardia Vieja"
cp -R -f "Tango Argentin/Juan Maglio/Juan Maglio - 1927-1932 La Guardia Vieja/" "/Users/michelvargoz/Music/Tango Argentin/Juan Maglio/Juan Maglio - 1927-1932 La Guardia Vieja"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 1"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 1/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 2"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 2/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 3"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 3/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - 1935-1939 Tango Tunes Todo de Juan 3"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 03-1937"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 03-1937/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 03-1937"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 04-1937-1938"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 04-1937-1938/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 04-1937-1938"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 05-1938-1939"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 05-1938-1939/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa Vol 05-1938-1939"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 06-1939-1940"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 06-1939-1940/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 06-1939-1940"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 07-1940-1941"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 07-1940-1941/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 07-1940-1941"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 08-1941"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 08-1941/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 08-1941"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 09-1941-1942"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 09-1941-1942/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 09-1941-1942"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 11-1943"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 11-1943/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 11-1943"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 12-1944"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 12-1944/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 12-1944"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 13-1944-1945"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 13-1944-1945/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 13-1944-1945"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 14-1945-1946"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 14-1945-1946/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 14-1945-1946"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 15-1946-1947"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 15-1946-1947/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 15-1946-1947"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 18-1949-1950"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 18-1949-1950/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 18-1949-1950"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 19-1950-1951"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 19-1950-1951/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 19-1950-1951"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 20-1951-1952"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 20-1951-1952/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 20-1951-1952"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 21-1952-1953"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 21-1952-1953/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 21-1952-1953"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 22-1953-1954"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 22-1953-1954/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 22-1953-1954"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 24-1955-1956"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 24-1955-1956/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 24-1955-1956"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 25-1956-1957"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 25-1956-1957/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 25-1956-1957"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 26-1957-1958"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 26-1957-1958/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 26-1957-1958"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 27-1958"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 27-1958/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 27-1958"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 28-1958"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 28-1958/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 28-1958"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 29-1958-1959"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 29-1958-1959/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 29-1958-1959"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 30-1959-1960"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 30-1959-1960/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 30-1959-1960"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 31-1960-1961"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 31-1960-1961/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 31-1960-1961"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 32-1961"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 32-1961/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 32-1961"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 33-1961-1962"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 33-1961-1962/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 33-1961-1962"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 35-1963"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 35-1963/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 35-1963"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 36-1963-1964"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 36-1963-1964/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 36-1963-1964"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 39-1965-1966"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 39-1965-1966/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 39-1965-1966"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 41-1967"
cp -R -f "Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 41-1967/" "/Users/michelvargoz/Music/Tango Argentin/Juan d'Arienzo/Juan d'Arienzo - Su obra completa vol 41-1967"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 1924 1928 - Todo Corazón"
cp -R -f "Tango Argentin/Julio de Caro/Julio De Caro - 1924 1928 - Todo Corazón/" "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 1924 1928 - Todo Corazón"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 1926-1932"
cp -R -f "Tango Argentin/Julio de Caro/Julio De Caro - 1926-1932/" "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 1926-1932"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 40 grandes exitos"
cp -R -f "Tango Argentin/Julio de Caro/Julio De Caro - 40 grandes exitos/" "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - 40 grandes exitos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - Tangos de rompe y raja"
cp -R -f "Tango Argentin/Julio de Caro/Julio De Caro - Tangos de rompe y raja/" "/Users/michelvargoz/Music/Tango Argentin/Julio de Caro/Julio De Caro - Tangos de rompe y raja"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Lucio Demare/Lucio Demare - Sus Éxitos Con Miranda, Berón y Quintana"
cp -R -f "Tango Argentin/Lucio Demare/Lucio Demare - Sus Éxitos Con Miranda, Berón y Quintana/" "/Users/michelvargoz/Music/Tango Argentin/Lucio Demare/Lucio Demare - Sus Éxitos Con Miranda, Berón y Quintana"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Lucio Demare/Lucio Demare Su Obra Completa"
cp -R -f "Tango Argentin/Lucio Demare/Lucio Demare Su Obra Completa/" "/Users/michelvargoz/Music/Tango Argentin/Lucio Demare/Lucio Demare Su Obra Completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Calo - 1941-1945 Al compás del corazón (Tango Tunes)"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Calo - 1941-1945 Al compás del corazón (Tango Tunes)/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Calo - 1941-1945 Al compás del corazón (Tango Tunes)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Calo - 1942-1944 Inspiracion"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Calo - 1942-1944 Inspiracion/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Calo - 1942-1944 Inspiracion"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1941-1943 Cuatro Compases"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - 1941-1943 Cuatro Compases/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1941-1943 Cuatro Compases"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1941-1963 Yo soy el tango"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - 1941-1963 Yo soy el tango/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1941-1963 Yo soy el tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1943-1943 Cuatro compases Vol 2"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - 1943-1943 Cuatro compases Vol 2/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1943-1943 Cuatro compases Vol 2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1943-1944 Cuatro compases Vol 3"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - 1943-1944 Cuatro compases Vol 3/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1943-1944 Cuatro compases Vol 3"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1944-1945 Cuatro compases Vol 4"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - 1944-1945 Cuatro compases Vol 4/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - 1944-1945 Cuatro compases Vol 4"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - Lo mejor de Miguel Caló V2"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló - Lo mejor de Miguel Caló V2/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló - Lo mejor de Miguel Caló V2"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló su obra"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló su obra/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló su obra"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló y Lucho Gatica - Tangos del recuerdo"
cp -R -f "Tango Argentin/Miguel Calo/Miguel Caló y Lucho Gatica - Tangos del recuerdo/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Calo/Miguel Caló y Lucho Gatica - Tangos del recuerdo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Album inconnu"
cp -R -f "Tango Argentin/Miguel Villasboas/Miguel Villasboas - Album inconnu/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Album inconnu"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Miguel Villaboas en Japon 2001"
cp -R -f "Tango Argentin/Miguel Villasboas/Miguel Villasboas - Miguel Villaboas en Japon 2001/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Miguel Villaboas en Japon 2001"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Tango Rioplatense"
cp -R -f "Tango Argentin/Miguel Villasboas/Miguel Villasboas - Tango Rioplatense/" "/Users/michelvargoz/Music/Tango Argentin/Miguel Villasboas/Miguel Villasboas - Tango Rioplatense"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1927-1928 Maldonado"
cp -R -f "Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1927-1928 Maldonado/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1927-1928 Maldonado"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1932-1980 Todas sus grabaciones"
cp -R -f "Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1932-1980 Todas sus grabaciones/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1932-1980 Todas sus grabaciones"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1935 Tango Tunes canta Roberto Ray"
cp -R -f "Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1935 Tango Tunes canta Roberto Ray/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1935 Tango Tunes canta Roberto Ray"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1937 Vida Mia canta Roberto Ray"
cp -R -f "Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1937 Vida Mia canta Roberto Ray/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1933-1937 Vida Mia canta Roberto Ray"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1950-1957 con Hector Pacheco Coleccion Pagina 12 vol 1"
cp -R -f "Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1950-1957 con Hector Pacheco Coleccion Pagina 12 vol 1/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Fresedo/Osvaldo Fresedo - 1950-1957 con Hector Pacheco Coleccion Pagina 12 vol 1"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - 1943-1945 Tango Tunes San Pugliese"
cp -R -f "Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - 1943-1945 Tango Tunes San Pugliese/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - 1943-1945 Tango Tunes San Pugliese"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - con Alberto Morán"
cp -R -f "Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - con Alberto Morán/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese - con Alberto Morán"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese discographie"
cp -R -f "Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese discographie/" "/Users/michelvargoz/Music/Tango Argentin/Osvaldo Pugliese/Osvaldo Pugliese discographie"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Pedro Laurenz/Pedro Laurenz Su obra completa"
cp -R -f "Tango Argentin/Pedro Laurenz/Pedro Laurenz Su obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Pedro Laurenz/Pedro Laurenz Su obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Rafael Canaro/Rafael Canaro 70 Temas"
cp -R -f "Tango Argentin/Rafael Canaro/Rafael Canaro 70 Temas/" "/Users/michelvargoz/Music/Tango Argentin/Rafael Canaro/Rafael Canaro 70 Temas"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Ricardo Malerba/Ricardo Malerba su obra completa"
cp -R -f "Tango Argentin/Ricardo Malerba/Ricardo Malerba su obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Ricardo Malerba/Ricardo Malerba su obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Ricardo Tanturi/Ricardo Tanturi Su obra completa"
cp -R -f "Tango Argentin/Ricardo Tanturi/Ricardo Tanturi Su obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Ricardo Tanturi/Ricardo Tanturi Su obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Las Milongas más Milonga (Quinteto Pirincho & Roberto Firpo)"
cp -R -f "Tango Argentin/Roberto Firpo/Las Milongas más Milonga (Quinteto Pirincho & Roberto Firpo)/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Las Milongas más Milonga (Quinteto Pirincho & Roberto Firpo)"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1944"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1944/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1944"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1956 Grandes del tango"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1956 Grandes del tango/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1920-1956 Grandes del tango"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1950 De La Guardia Vieja Reliquias"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1950 De La Guardia Vieja Reliquias/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1950 De La Guardia Vieja Reliquias"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1953 Alma de bohemio"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1953 Alma de bohemio/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1936-1953 Alma de bohemio"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1954 Serie de Oro"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1954 Serie de Oro/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1954 Serie de Oro"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1960 Tangos y Valsecitos"
cp -R -f "Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1960 Tangos y Valsecitos/" "/Users/michelvargoz/Music/Tango Argentin/Roberto Firpo/Roberto Firpo - 1937-1960 Tangos y Valsecitos"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1940 Tango Tunes Todo de Rodolfo"
cp -R -f "Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1940 Tango Tunes Todo de Rodolfo/" "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1940 Tango Tunes Todo de Rodolfo"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1951 Al Compás del Vals"
cp -R -f "Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1951 Al Compás del Vals/" "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - 1938-1951 Al Compás del Vals"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - Su obra completa"
cp -R -f "Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - Su obra completa/" "/Users/michelvargoz/Music/Tango Argentin/Rodolfo Biagi/Rodolfo Biagi - Su obra completa"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Romeo Gavioli/Romeo Gavioli -  Candombes"
cp -R -f "Tango Argentin/Romeo Gavioli/Romeo Gavioli -  Candombes/" "/Users/michelvargoz/Music/Tango Argentin/Romeo Gavioli/Romeo Gavioli -  Candombes"
mkdir -p "/Users/michelvargoz/Music/Tango Argentin/Romeo Gavioli/Romeo Gavioli - Lo mejor de Romeo Gavioli"
cp -R -f "Tango Argentin/Romeo Gavioli/Romeo Gavioli - Lo mejor de Romeo Gavioli/" "/Users/michelvargoz/Music/Tango Argentin/Romeo Gavioli/Romeo Gavioli - Lo mejor de Romeo Gavioli"
mkdir -p "/Users/michelvargoz/Music/Variété&jazz/Variété/\$Hits"
cp -R -f "Variété&jazz/Variété/\$Hits/" "/Users/michelvargoz/Music/Variété&jazz/Variété/\$Hits"
mkdir -p "/Users/michelvargoz/Music/Variété&jazz/Variété/Gloria Gaynor"
cp -R -f "Variété&jazz/Variété/Gloria Gaynor/" "/Users/michelvargoz/Music/Variété&jazz/Variété/Gloria Gaynor"
